### ISSUE TITLE
ruby-head does not compile on OS X

### ISSUE THREAD

**Issue by BanzaiMan** [wayneeseguin/rvm#3177]
https://travis-ci.org/travis-ci/travis-rubies/jobs/42947853#L261

```
    undefined method `hexdigest' for #<OpenSSL::Digest:0x007ff739a21150>
```

The same commit compiles fine on Linux.

**Comment by mpapis** [comment]
as I understand this is fixed in ruby-2.0.0

**Comment by BanzaiMan** [comment]
Can this be reopened?

The original issue was not so much a failure to compile on OS X, but the inability to use HTTPS when using `gem`. At the moment, the check to install `bundler` on [`ruby-head(-clang)` is disabled](https://github.com/travis-ci/travis-rubies/blob/8fbf55f25ced417cd9567be6e1959eaedabe396c/build.sh#L131-L133). This could be potentially a reason for travis-ci/travis-ci#3985.

https://github.com/travis-ci/travis-ci/issues/3985#issuecomment-107042354 suggests a workaround, but I do not know how to test it with RVM controlling the build process.

(I am also OK with opening a separate issue.)

**Comment by mpapis** [comment]
please open a new ticket please
