### ISSUE TITLE
RHEL6 issue downloading versions of Ruby.

### ISSUE THREAD

**Issue by samrocketman** [wayneeseguin/rvm#3178]
I'll post more details about this tomorrow when I'm at work.  This is related to #2583.

**Comment by mpapis** [comment]
so any updates on the tests with rubies listed here <https://rvm.io/binaries>?

**Comment by samrocketman** [comment]
I installed and tested ruby 2.1.5 without issue.  I've been using it for a few weeks now.

**Comment by mpapis** [comment]
could you test if all other rubies listed here <https://rvm.io/binaries/centos/6/x86_64/> also work, something simple like bellow would be enough:
```bash
gem list
ruby -ryaml -rreadline -ropenssl -e 'puts "ok: "+YAML.to_s'
```

**Comment by samrocketman** [comment]
How do I force it to use rvm.io only for downloads?  Last I tried it; it used the first available mirror (not rvm.io).  It would be more useful to test rvm.io directly I think.  Unless you don't think that is an issue.

**Comment by mpapis** [comment]
closing as there was no feedback in quite some time

**Comment by samrocketman** [comment]
Fair enough, sorry about that.  At this point we've begun migrating to CentOS so it hasn't been much of an issue.
