### ISSUE TITLE
Cannot install jgio on cents

### ISSUE THREAD

**Issue by sokrate** [wayneeseguin/rvm#3186]
Hello, I'm trying to install kgio gem on centos 6 server, but i'm got next error:

gem install kgio
Building native extensions.  This could take a while...
ERROR:  Error installing kgio:
	ERROR: Failed to build gem native extension.

    /home/userhome/.rvm/rubies/ruby-1.9.3-p551/bin/ruby -r ./siteconf20141208-36471-1fsmpl.rb extconf.rb
checking for CLOCK_MONOTONIC in time.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/home/userhome/.rvm/rubies/ruby-1.9.3-p551/bin/ruby
/home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:381:in `try_do': The compiler failed to generate an executable file. (RuntimeError)
You have to install development tools first.
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:491:in `block in try_compile'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:443:in `with_werror'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:491:in `try_compile'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:686:in `macro_defined?'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:822:in `block in have_macro'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:790:in `block in checking_for'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:284:in `block (2 levels) in postpone'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:284:in `block in postpone'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:254:in `open'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:280:in `postpone'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:789:in `checking_for'
	from /home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib/ruby/1.9.1/mkmf.rb:821:in `have_macro'
	from extconf.rb:5:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /home/userhome/.rvm/gems/ruby-1.9.3-p551/gems/kgio-2.9.2 for inspection.
Results logged to /home/userhome/.rvm/gems/ruby-1.9.3-p551/extensions/x86_64-linux/1.9.1/kgio-2.9.2/gem_make.out

mkmf.log output:

" -o conftest -I/home/userhome/.rvm/rubies/ruby-1.9.3-p551/include/ruby-1.9.1/x86_64-linux -I/home/userhome/.rvm/rubies/ruby-1.9.3-p551/include/ruby-1.9.1/ruby/backward -I/home/userhome/.rvm/rubies/ruby-1.9.3-p551/include/ruby-1.9.1 -I.    -D_GNU_SOURCE -DPOSIX_C_SOURCE=1-D_POSIX_C_SOURCE=200112L  -O3 -ggdb -Wall -Wextra -Wno-unused-parameter -Wno-parentheses -Wno-long-long -Wno-missing-field-initializers -Wpointer-arith -Wwrite-strings -Wdeclaration-after-statement -Wimplicit-function-declaration  -fPIC conftest.c  -L. -L/home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib -Wl,-R/home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib -L.  -rdynamic -Wl,-export-dynamic     '-Wl,-rpath,/../lib' -Wl,-R -Wl,/home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib -L/home/userhome/.rvm/rubies/ruby-1.9.3-p551/lib -lruby  -lpthread -lrt -ldl -lcrypt -lm   -lc"
sh: - : invalid option
Usage:  sh [GNU long option] [option] ...
        sh [GNU long option] [option] script-file ...
GNU long options:
        --debug
        --debugger
        --dump-po-strings
        --dump-strings
        --help
        --init-file
        --login
        --noediting
        --noprofile
        --norc
        --posix
        --protected
        --rcfile
        --rpm-requires
        --restricted
        --verbose
        --version
Shell options:
        -irsD or -c command or -O shopt_option          (invocation only)
        -abefhkmnptuvxBCHP or -o option
allexport       off
braceexpand     on
emacs           on
errexit         off
errtrace        off
functrace       off
hashall         on
histexpand      on
history         on
ignoreeof       off
interactive-comments    on
keyword         off
monitor         off
noclobber       off
noexec          off
noglob          off
nolog           off
notify          off
nounset         off
onecmd          off
physical        off
pipefail        off
posix           off
privileged      off
verbose         off
vi              off
xtrace          off
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */

May be somebody know how I can fix this error.

**Comment by mpapis** [comment]
closing as it has been almost a month with no feedback
