### ISSUE TITLE
RVM installer adds path extension lines to bashrc, even if present.

### ISSUE THREAD

**Issue by TheKevJames** [wayneeseguin/rvm#3188]
Command in `rvm/scripts/functions/installer` on line 919 (`print_etc_bashrc_change()`) does not check whether rvm bin is already in the system path before appending to bashrc, zlogin, etc.

This occurs for me whenever I run any form of rvm update, for example `rvm get latest`. Before update, my zshrc looks like:

```
### ~/.zshrc
source ~/.zsh/path.zsh

# other things....
```

```
### ~/.zsh/path.zsh
# various path modifications

export PATH=$HOME/.rvm/bin:$PATH
```

And after, I have

```
### ~/.zshrc
source ~/.zsh/path/zsh

# other things....

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
```

My ~/.profile file is also modified:

```
### ~/.profile
# things

export PATH="$PATH:$HOME/.rvm/bin" # Add RVM to PATH for scripting
[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*
```

Note that the source line is included by profile already with `source ~/.zsh/dev.zsh`.

**Comment by mpapis** [comment]
closing as it has been almost a month with no feedback
