### ISSUE TITLE
Unexpected EOF errors in 1.26.4 on Debian Jessie

### ISSUE THREAD

**Issue by aef** [wayneeseguin/rvm#3199]
On Debian Jessie, with RVM 1.26.4 I get the following error messages when executing some sub-commands. For example, the "list known" sub-command does not output anything else than the aforementioned message.

    /usr/local/rvm/scripts/functions/utility_logging: eval: line 131: unexpected EOF while looking for matching `"'
    /usr/local/rvm/scripts/functions/utility_logging: eval: line 132: syntax error: unexpected end of file

**Comment by mpapis** [comment]
closing as it has been over three weeks with no feedback
