### ISSUE TITLE
No fallback URL can be calculated for ftp://xmlsoft.org/libxslt/libxslt-1.1.26.tar.gz, and ftp://xmlsoft.org/libxml2/libxml2-2.7.3.tar.gz,

### ISSUE THREAD

**Issue by engagamil** [wayneeseguin/rvm#3209]
Fetching libxslt-1.1.26.tar.gz to /usr/local/rvm/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to xmlsoft.org:21; No route to host
There was an error(7).

No fallback URL can be calculated for ftp://xmlsoft.org/libxslt/libxslt-1.1.26.tar.gz, 

================================================

Fetching libxml2-2.7.3.tar.gz to /usr/local/rvm/archives
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0curl: (7) Failed connect to xmlsoft.org:21; No route to host
There was an error(7).

No fallback URL can be calculated for ftp://xmlsoft.org/libxml2/libxml2-2.7.3.tar.gz,

**Comment by mpapis** [comment]
closing as there was no feedback in two weeks, let me know if you can provide more details and I will reopen

**Comment by SarpongAbasimi** [comment]
Having the same problem.

chriss-MBP% which ruby
/usr/bin/ruby
chriss-MBP% ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
chriss-MBP% rbenv install 2.6.0
zsh: command not found: rbenv
chriss-MBP% rbenv install 2.6
zsh: command not found: rbenv
chriss-MBP% brew update
Already up-to-date.
chriss-MBP% rvm install ruby 2.5.0
Warning, new version of rvm available '1.29.8', you are using older version '1.29.7-next'.
You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
ruby-2.5.0 - #removing src/ruby-2.5.0 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.13/x86_64/ruby-2.5.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/chrissongz/.rvm/rubies/ruby-2.5.0, this may take a while depending on your cpu(s)...
ruby-2.5.0 - #downloading ruby-2.5.0, this may take a while depending on your connection...
/Users/chrissongz/.rvm/scripts/functions/support: line 170: cd: /Users/chrissongz/.rvm/archives: No such file or directory
curl: (3) <url> malformed
There was an error(3).

No fallback URL can be calculated for /2.5/ruby-2.5.0.tar.bz2, open a ticket with full output here:

    https://github.com/rvm/rvm/issues


There has been an error fetching the ruby interpreter. Halting the installation.
chriss-MBP% rvm info system

system:

  system:
    uname:        "Darwin chriss-MBP 17.7.0 Darwin Kernel Version 17.7.0: Thu Jun 21 22:53:14 PDT 2018; root:xnu-4570.71.2~1/RELEASE_X86_64 x86_64"
    name:         "OSX"
    version:      "10.13"
    architecture: "x86_64"
    bash:         "/bin/bash => GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin17)"
    zsh:          "/bin/zsh => zsh 5.3 (x86_64-apple-darwin17.0)"
    remote_path:  "osx/10.13/x86_64"
    xcode:        "10.1"
chriss-MBP%
