### ISSUE TITLE
Using RVM only to install MRI rubies in a custom location (not hook into bash init scripts or anything else)

### ISSUE THREAD

**Issue by thewoolleyman** [wayneeseguin/rvm#3210]
Hi,

I like how RVM automatically handles MRI ruby installation issues - e.g. installing dependencies, applying patches, fixing permissions, etc.

However, I'd like to be able to use ONLY this install functionality, AND also have RVM install the ruby in a custom location (e.g. /usr/local/) - but WITHOUT having to "use" rvm to manage current interpreter (i.e., don't put it in my bash scripts or modify anything else on my system).

This is useful in scenarios like Docker images, where I want RVM to automatically handle ruby installation issues that ruby-install or ruby-build blows up on, but I will only have a single interpreter installed, so I don't need RVM hooked into my shell (i.e. I can use chruby).

Is this possible?

Thanks,
-- Chad

**Comment by mpapis** [comment]
closing as there was no feedback in two weeks, let me know if you can provide more details and I will reopen

**Comment by thewoolleyman** [comment]
No, this response is fine - sorry I didn't say you could close.  Thanks for the prompt response!

**Comment by mpapis** [comment]
you are welcome, let me know if you need more help
