### ISSUE TITLE
Help old rubies build on newer Macs

### ISSUE THREAD

**Issue by mcandre** [wayneeseguin/rvm#3217]
When building older Rubies (e.g. ruby1.8, ruby1.9) on newer Macs (e.g. 10.9 Mavericks, 10.10 Yosemite), please automatically apply the `—with-gcc=clang` flag, as the rubies fail to build otherwise. Thank you.

See https://github.com/rvm/rvm/issues/10.

**Comment by mpapis** [comment]
closing as there was no feedback in two weeks, please let me know if you can provide more details and I will reopen
