### ISSUE TITLE
“stat: cannot read file system information for ‘%u:%g’: No such file or directory”

### ISSUE THREAD

**Issue by bdesham** [wayneeseguin/rvm#3222]
Below is the transcript of a terminal session I just had. I wanted to install a new Ruby; RVM told me that it was out of date so I aborted the installation, added “rvm_autoupdate_flag=2” to my rvmrc, and then retried the installation. It seems to have actually worked—I was able to install some gems and run irb—but I got a whole bunch of “no such file or directory” notices. I’m using zsh 5.0.7 on OS X 10.10.1. Any idea what’s going wrong here?

    $ rvm install 2.1.2-jekyll
    Warning, new version of rvm available '1.26.5', you are using older version '1.25.30'.
    You can disable this warning with:    echo rvm_autoupdate_flag=0 >> ~/.rvmrc
    You can enable  auto-update  with:    echo rvm_autoupdate_flag=2 >> ~/.rvmrc
    Searching for binary rubies, this might take some time.
    Found remote file https://rvm.io/binaries/osx/10.10/x86_64/ruby-2.1.2.tar.bz2
    Checking requirements for osx.
    ^C
    $ echo rvm_autoupdate_flag=2 >> ~/.rvmrc
    $ rvm install 2.1.2-jekyll             
    Found old RVM 1.25.30 - updating.
    Downloading https://get.rvm.io
    Downloading https://github.com/wayneeseguin/rvm/archive/master.tar.gz
    
    Upgrading the RVM installation in /Users/bdesham/.rvm/
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    chown: invalid user: ‘  File: "/Users/bdesham/.rvmrc"\n    ID: 100000500000011 Namelen: *       Type: hfs\nBlock size: 4096       Fundamental block size: 4096\nBlocks: Total: 218996479  Free: 171995902  Available: 171931902\nInodes: Total: 218996477  Free: 171931902’
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
        RVM PATH line found in /Users/bdesham/.profile /Users/bdesham/.bashrc.
        RVM PATH line not found for Zsh, rerun this command with '--auto-dotfiles' flag to fix it.
        RVM sourcing line found in /Users/bdesham/.bash_profile /Users/bdesham/.zshrc.
    Upgrade of RVM in /Users/bdesham/.rvm/ is complete.
    
    # User Name,
    #
    #   Thank you for using RVM!
    #   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
    #
    # ~Wayne, Michal & team.
    
    In case of problems: http://rvm.io/help and https://twitter.com/rvm_io
    
    Upgrade Notes:
    
      * It looks like some old stuff is laying around RVM, you can cleanup with: rvm cleanup all
    
      * No new notes to display.
    
    RVM reloaded!
    Searching for binary rubies, this might take some time.
    Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.1.2.tar.bz2
    Checking requirements for osx.
    Uninstalling /usr/local/Cellar/gcc46/4.6.4...
    Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
    Requirements installation successful.
    ruby-2.1.2-jekyll - #configure
    ruby-2.1.2-jekyll - #download
      % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                     Dload  Upload   Total   Spent    Left  Speed
    100 6678k  100 6678k    0     0   513k      0  0:00:13  0:00:13 --:--:--  635k
    No checksum for downloaded archive, recording checksum in user configuration.
    ruby-2.1.2-jekyll - #validate archive
    ruby-2.1.2-jekyll - #extract
    ruby-2.1.2-jekyll - #validate binary
    ruby-2.1.2-jekyll - #setup
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    ruby-2.1.2-jekyll - #gemset created /Users/bdesham/.rvm/gems/ruby-2.1.2-jekyll@global
    ruby-2.1.2-jekyll - #importing gemset /Users/bdesham/.rvm/gemsets/global.gems........................................-
    ruby-2.1.2-jekyll - #generating global wrappers........
    ruby-2.1.2-jekyll - #gemset created /Users/bdesham/.rvm/gems/ruby-2.1.2-jekyll
    ruby-2.1.2-jekyll - #importing gemsetfile /Users/bdesham/.rvm/gemsets/default.gems evaluated to empty gem list
    ruby-2.1.2-jekyll - #generating default wrappers........
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    chown: invalid user: ‘  File: "/Users/bdesham/.rvm/user/installs"\n    ID: 100000500000011 Namelen: *       Type: hfs\nBlock size: 4096       Fundamental block size: 4096\nBlocks: Total: 218996479  Free: 172015408  Available: 171951408\nInodes: Total: 218996477  Free: 171951408’
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    stat: cannot read file system information for ‘%u:%g’: No such file or directory
    $

**Comment by feniix** [comment]
Hi, 

I am running into this same issue.

Info that could be helpful:
rvm 1.26.5 + 'rvm install ruby-2.1.5' 
``` 
ruby-2.1.5 - #setup
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
stat: cannot read file system information for ‘%u:%g’: No such file or directory
```


rvm 1.26.4 + 'rvm install ruby-2.1.5' = no error

**Comment by mpapis** [comment]
please try with `rvm get head`

**Comment by rmbl** [comment]
Installed ruby 2.1.5 with the head version of rvm and I didn't get any errors. Looks good.

**Comment by feniix** [comment]
Fixed now 

2.1.5 and 2.2.0 installed perfectly with HEAD

**Comment by mpapis** [comment]
thanks for confirming
