### ISSUE TITLE
Warning during Install of latest Ruby

### ISSUE THREAD

**Issue by zaji** [wayneeseguin/rvm#3224]
Should I be concerned with this part of message after installation?

gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.

Then it gives me a Primary key fingerprint and Subkey fingerprint that do not mach.

**Comment by mpapis** [comment]
closing as there was no feedback in two weeks, please let me know if you can provide more details and I will reopen
