### ISSUE TITLE
RVM should support --offline flag

### ISSUE THREAD

**Issue by samdunne** [wayneeseguin/rvm#3246]
So if a flag such as ```--offline``` is used (```rvm install ruby-<version> --offline```) then rvm will look to it's archives folder for a ruby to install and wont attempt to access the internet at all.

Alternatively an ```--archive``` flag where you can specify a specic ```.tar.bz2``` file to use for installation and once again not try to access the internet.

I can look at trying to implement this if there is interest.

**Comment by mpapis** [comment]
this is a feature request, RVM1 is closed for future requests, both options will be in RVM2 - closing, if you need this features in RVM1 feel free to implement, I will be happy to review and merge a pull request

**Comment by samdunne** [comment]
Apologies. RVM2 sounds great! Might try implement it for 1.X in the mean time anyway :)
