### ISSUE TITLE
Unable to install ruby 2.2.0 with rvm

### ISSUE THREAD

**Issue by mattangriffel** [wayneeseguin/rvm#3247]
Getting an error installing ruby 2.2.0 that has been really hard to troubleshoot

The core of the error seems to be (during compiling):

````
ld: warning: ignoring file libruby.2.2.0-static.a, file was built for archive which is not the architecture being linked (x86_64): libruby.2.2.0-static.a
Undefined symbols for architecture x86_64:
  "_ruby_init", referenced from:
      _main in main.o
  "_ruby_init_stack", referenced from:
      _main in main.o
  "_ruby_options", referenced from:
      _main in main.o
  "_ruby_run_node", referenced from:
      _main in main.o
  "_ruby_sysinit", referenced from:
      _main in main.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
(Here's a gist of the whole error: https://gist.github.com/mattangriffel/e47c5638dc08fcbb5074)

I've tried a variety of solutions:
Updating rvm to stable and head
Cleaning up my homebrew
Making sure xcode-select is up to date
Manually setting my ARCHFLAGS

Nothing yet. Anyone seen this before?

**Comment by mpapis** [comment]
try:
```bash
rvm install 2.2.0 -- --disable-static
```

**Comment by mattangriffel** [comment]
@mpapis nah I run into the same error

**Comment by mpapis** [comment]
try:
```bash
rvm install 2.2.0 --64
```

**Comment by mattangriffel** [comment]
same error

**Comment by mpapis** [comment]
did you upgrade OSX?

**Comment by mattangriffel** [comment]
Yep, I'm on 10.10.1

**Comment by mpapis** [comment]
on upgraded OSX bad things happen, I recommend you remove all packages from homebrew / macports and let the rvm installation install what's missing

**Comment by mattangriffel** [comment]
Hmm, I've removed MacPorts entirely and uninstalled all homebrew packages, ran rvm autolibs enable, and still getting the same error.

**Comment by mpapis** [comment]
what version of rvm is it, can I see exact command you run, all it's output, mentioned log file and `env | sort` - please [gist it](https://gist.github.com)

**Comment by mattangriffel** [comment]
Yep – right now I'm running rvm 1.26.7 (latest) but the problem persist on head as well. [Here's a gist](https://gist.github.com/mattangriffel/eae87beff85fa18bdb5f) of all of that.

**Comment by mpapis** [comment]
hmm, there has to be some old artifacts from previous version of OSX, did you also install new Xcode after upgrade?

**Comment by mattangriffel** [comment]
I agree, probably something leftover. Just removed xcode and xcode-beta entirely, and removed and reinstalled xcode-select, but the same error is still happening.

**Comment by mpapis** [comment]
how did you remove all the packages from homebrew? I'm wondering if there could be something that was not removed?

**Comment by mattangriffel** [comment]
`brew remove --force $(brew list)` and then `brew list` showed no packages. Though during rvm install 2.2.0 rvm uses brew to install autoconf, automake, libgpg-error, libksba, libtool, libyaml, openssl, pkg-config, and readline

**Comment by mpapis** [comment]
how about macports? maybe there was yet another package manager? ... this should not happen, any chance you could just reinstall this system?

**Comment by mattangriffel** [comment]
Don't have Macports installed. Do you mean reinstall 10.10?

**Comment by mpapis** [comment]
yes clean the disk and reinstall, would that be possible?

**Comment by mattangriffel** [comment]
Ideally not, but if it comes down to it I'll probably have it. It seems like overkill and thinking of switching to rbenv to see if that solves it.

**Comment by mpapis** [comment]
you do not have to switch to try out if that works, use [ruby-install](https://github.com/postmodern/ruby-install) or [ruby-build](https://github.com/sstephenson/ruby-build) - then you can mount this rubies into RVM with:
```bash
rvm mount /path/to/new/ruby
```

**Comment by mattangriffel** [comment]
rbenv install worked just fine

**Comment by mpapis** [comment]
`ruby-build` has limited support for `homebrew` this would mean there could be still artifacts in homebrew that impact the installation of packages, we have two options now:
1. you can help me finish debugging it (which most likely will end up in cleaning up `homebrew` caches or build locations,
2. we can close the issue as your problem is solved

**Comment by mpapis** [comment]
closing - if anyone has similar problem please open new ticket with details

**Comment by jclusso** [comment]
> `brew remove --force $(brew list)` and then `brew list` showed no packages. Though during rvm install 2.2.0 rvm uses brew to install autoconf, automake, libgpg-error, libksba, libtool, libyaml, openssl, pkg-config, and readline

This sucked because I had to reinstall all of my packages but it fixed my problem. Wish I knew which package screwed my shit up. I was getting this error on 2.4.3
