### ISSUE TITLE
RVM intercepting script commands.

### ISSUE THREAD

**Issue by snarke** [wayneeseguin/rvm#3249]
I have a directory where I keep various Bash scripts. It's the first directory in my $PATH. One of the scripts is named "typeset" and its job is to run XeLaTeX so that I can typeset books. However, RVM is blocking access to my script. It seems to have some command of its own with the same name. There's no mention of it in the man pages. How do I get RVM to quit interfering with my scripts?

**Comment by mpapis** [comment]
`typeset` is another version of `local` which is basically saying define local variables, I will investigate if it's possible to escape them

**Comment by mpapis** [comment]
try with `rvm get head`

**Comment by snarke** [comment]
Try "with" 'rvm get head'? with what? Are you saying to try that in combination with 'escape all typset?'

**Comment by mpapis** [comment]
when you run `rvm get head` you will get the RVM version with escapes, does it still show any problems?

**Comment by snarke** [comment]
`$ escape all typeset`
`-bash: escape: command not found`

`rvm get head` got me quite a bit of commentary. 
`Warning! PATH is not properly set up, '/Users/snarke/.rvm/gems/ruby-2.1.3/bin' is not at first place,`
yea, no kidding. That's on purpose, RVM. :/  Then there was an `Error running 'command gem install /Users/snarke/.rvm/gem-cache/gem-wrappers-1.2.7.gem --local --no-ri --no-rdoc',`

I've temporarily patched the problem with `alias typeset=~/.scripts/typeset`, but meh.

**Comment by mpapis** [comment]
maybe I need  more explanation what your problem is, is it you need your prefix in `PATH`? there is `rvm_user_path_prefix` which should do automatically set up `PATH` for you -- it's not yet detected in the warning you mention, but that can be fixed, try:
```bash
echo rvm_user_path_prefix=/path/to/yours/bash/scripts >> ~/.rvmrc
```
if this helps and you still see the warning in `rvm get head` - let me know, I will improve it to ignore the `rvm_user_path_prefix`.

**Comment by snarke** [comment]
When I open a terminal window and type `$ typeset texfile` I want that to function as if I'd typed `$ ~/.scripts/typeset texfile` Bash scripts in my ~/.scripts directory should have priority over anything else in my command environment except for built-in commands.

**Comment by mpapis** [comment]
first you need:
```bash
echo rvm_user_path_prefix=$HOME/.scripts >> ~/.rvmrc
```
it will tell RVM to always prefix this path to `$PATH`

then you need to add:
```bash
export PATH="$HOME/.scripts:$PATH"
```
to `~/.bash_profile` after sourcing RVM

**Comment by snarke** [comment]
I'm not totally happy about `rvm get head` either, since it triggers a download/install sequence. :/

`Warning! PATH is not properly set up, '/Users/snarke/.rvm/gems/ruby-2.1.3/bin' is not at first place,
         usually this is caused by shell initialization files - check them for 'PATH=...' entries,
         it might also help to re-add RVM to your dotfiles: 'rvm get stable --auto-dotfiles',
         to fix temporarily in this shell session run: 'rvm use ruby-2.1.3'.
Downloading https://get.rvm.io
No GPG software exists to validate rvm-installer, skipping.
Downloading https://github.com/wayneeseguin/rvm/archive/master.tar.gz
`

**Comment by mpapis** [comment]
the `Warning!` you see is not from update process itself, more commands will trigger it, it's the thing I need to fix, if you set `rvm_user_path_prefix` already and it still happens - I need to to add extra code to not warn about this path, as a bonus it will be set automatically as first for you even when you run `rvm use ...`

**Comment by snarke** [comment]
Okay, my .rvmrc file now has a line that says `rvm_user_path_prefix=/Users/snarke/.scripts` in it, and my .bash_profile file has `[[ -s "$HOME/.rvm/scripts/rvm" ]] && source "$HOME/.rvm/scripts/rvm" # Load RVM into a shell session *as a function*` as the next-to-last line, with `export PATH="$HOME/.scripts:$PATH" ` as the last line. 

However, if I type `typeset` at the prompt, I still get the massive script-dump of RVM-related stuff, rather than a complaint from XeTeX that I didn't give it a file name. :/

**Comment by mpapis** [comment]
can you run: `which -a typeset ; echo $PATH`

**Comment by snarke** [comment]
$ which -a typeset ; echo $PATH
~/.scripts:/Users/snarke/.rvm/gems/ruby-2.1.3/bin:/Users/snarke/.rvm/gems/ruby-2.1.3@global/bin:/Users/snarke/.rvm/rubies/ruby-2.1.3/bin:/Developer/Tools:/Library/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/usr/local/git/bin:/usr/texbin:/usr/X11/bin:/Users/snarke/.rvm/bin:/Users/snarke/.rvm/bin

**Comment by snarke** [comment]
`which -a typeset` by itself returns nothing at all.

**Comment by mpapis** [comment]
can I see `ls -l ~/.scripts/typeset`?

**Comment by snarke** [comment]
`$ ls -l ~/.scripts/typeset
-rwxrwxr-x@ 1 snarke  staff  350 Jan  4 15:21 /Users/snarke/.scripts/typeset
`

**Comment by mpapis** [comment]
your problem might be that `typeset` is a shell keyword, RVM does not do to this keyword itself exept of using it, if you have problems you should have same problems without RVM, can you try to rename the script to something else like `xltx` and run `hash -r` - does it run then without any problems?

**Comment by snarke** [comment]
Aha! I was blaming RVM because when I type `typeset` by itself I get a giant pile of this-and-that spilled across the screen which has lots of rvm-related material in it, But typing `typeset` on my XServe also spills text across the screen, and RVM isn't installed there. (It's actually running OSX 10.3, so it's got Ruby 1.8.6, and I don't install *anything* extra on that system unless it's desperately needed.)  

So this is all Bash's fault. Sorry for mistakenly dragging you in to this.

**Comment by mpapis** [comment]
ok then, closing the issue, escaped `typeset` might be useful later on in other shells ;)

**Comment by snarke** [comment]
For anybody else stumbling across this thread, my solution is to override the built-in command with an `alias typeset=~/.scripts/typeset` line in my .bash_profile file.
