### ISSUE TITLE
After upgrading to 1.26.8 .rvmrc is not loaded

### ISSUE THREAD

**Issue by timbru31** [wayneeseguin/rvm#3250]
When I `cd` into a directory with an `.rvmrc` in it, it doesn't load the `.rvmrc` anymore.
(rvm does notice the change and warns me about a modified file however)
This occurred when upgrading to 1.26.8 (1.26.7 is fine)

Running OS X 10.10.1, bash and zsh are affected.
Tried ruby-2.1.5 and ruby-2.2.0, same result.

Even such a simple `.rvmrc` is not loading anymore (I don't see "called" in my console)

````bash
#!/bin/sh
echo "called"
````

Did I miss something in the update that needs to be adjusted?
If you need more details, I'll try provide them asap.

Thanks for the great work and looking to hear from you,
Tim

**Comment by habermann24** [comment]
It seems that .rvmrc *is* loaded, but echo does not work within the rvmrc.
Try ```echo "called" > out.txt```. Somehow STDOUT won't be directed to the terminal anymore :-(

**Comment by mpapis** [comment]
try after:
```bash
rvm get head && rvm reload
```

**Comment by habermann24** [comment]
It works for me, thanks alot!!

**Comment by timbru31** [comment]
works again - thank you :smile:
