### ISSUE TITLE
problom with rvm install 1.9.2

### ISSUE THREAD

**Issue by schaer123** [wayneeseguin/rvm#3254]
when i did $ rvm install 1.9.2
i got this 

Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-1.9.2-p330.
It is not possible to build movable binaries for rubies 1.8-1.9.2, but you can do it for your system only.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.

RVM does not know how to build working ruby-1.9.2-p330 on OSX 10.10,
if you know please let us know by opening a ticket with instructions here:

    https://github.com/wayneeseguin/rvm/issues

**Comment by mpapis** [comment]
so do you know how to build movable binary for `1.9.2`?

**Comment by schaer123** [comment]
no i am i new at this hole thing

**Comment by mpapis** [comment]
then ignore this message, if you get problems the real cause has to be later - pleas [gist](https://gist.github.com) the command and whole output, include mentioned log file if any - if you ruby builds without problems - close the issue

**Comment by schaer123** [comment]
how do i close it @mpapis
