### ISSUE TITLE
intalling rails

### ISSUE THREAD

**Issue by schaer123** [wayneeseguin/rvm#3255]
i was trying to learn rails. i was was following the process on this website( http://edgeguides.rubyonrails.org/getting_started.html#guide-assumptions ) and i got this error at the install rails   ps i am doing this in terminal on a mac

Last login: Wed Jan  7 17:16:16 on ttys000
$-MBP-2:~ Samschaer$ sudo sh
Password:
sh-3.2# ruby -v
ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
sh-3.2# sqlite3 --version
3.8.5 2014-08-15 22:37:57 c8ade949d4a2eb3bba4702a4a0e17b405e9b6ace
sh-3.2# gem install rails
Building native extensions.  This could take a while...
ERROR:  Error installing rails:
	ERROR: Failed to build gem native extension.

    /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/include/ruby.h

Gem files will remain installed in /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.5 for inspection.
Results logged to /Library/Ruby/Gems/2.0.0/gems/nokogiri-1.6.5/ext/nokogiri/gem_make.out
sh-3.2#

**Comment by mpapis** [comment]
1) do not use `sudo` 2) do not use `sh` -- they are both starting new shell that either does not and can not load RVM

just run in your terminal (without `sudo` and `sh`):
```bash
rvm use ruby --install --default
gem install rails
rails ...
```
