### ISSUE TITLE
How to use RVM on tcsh based environment

### ISSUE THREAD

**Issue by vensridev** [wayneeseguin/rvm#3256]
Hi,

I have installed RVM using following procedure (https://rvm.io/rvm/install)

1. `curl -sSL https://get.rvm.io | bash -s stable --ruby --rails` - it has installed RVM (single-user) in $HOME. (Question: How do I specify a non-default RVM installation path in above command?)
2. Updated $PATH in my ~/.cshrc to have RVM bin path as below. `set path = ($HOME/.rvm/bin ${path})`

        prompt>which rvm 
        $HOME/.rvm/bin/rvm 
        prompt>rvm -v
         rvm 1.26.9 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
        prompt>rvm list
         rvm rubies
         # No rvm rubies installed yet. Try 'rvm help install'.

3. Though I have used --ruby and --rails in step (1), I noticed that Ruby & Rails were not installed as part of (1). So trying to install Ruby myself, using `rvm install ruby`

4. Per RVM installation instruction, I need to `source $HOME/.rvm/scripts/rvm`, which uses bash to execute. But our entire environment has tcsh as shell, and I cannot afford to change it. 

         prompt>source ~/.rvm/scripts/rvm
         if: Too few arguments.

   It is erroring out since our default shell is TCSH and the script is written in BASH.

         prompt> echo $SHELL
          /bin/tcsh

   And we use ~/.cshrc to configure our environment.

Can someone help me to fix the setup, so that I can use RVM?

Thanks in advance.

**Comment by vensridev** [comment]
I tried http://po-ru.com/diary/using-rvm-with-tcsh/ - No help
Currently using http://stackoverflow.com/questions/27380203/how-do-i-use-rvm-with-tcsh as workaround. Still `rvm use` does not work

**Comment by vensridev** [comment]
`rvm use` gives following message.
        prompt>rvm use 1.8.6-p383

        RVM is not a function, selecting rubies with 'rvm use ...' will not work.

        You need to change your terminal emulator preferences to allow login shell.
        Sometimes it is required to use `/bin/bash --login` as the command.
        Please visit https://rvm.io/integration/gnome-terminal/ for an example.
I tried 'Run command as a login shell', as well, it doesn't help. How do I fully utilize RVM power? Please help.

**Comment by mpapis** [comment]
RVM works interactively only with `bash` and `zsh`, whe used via `PATH` you can do all operations except of using rubies, you could overcome this limitation by writing a `tcsh` function for `rvm` which uses a trick to load rubies: (`sh` code)
```bash
rvm()
{
  \typeset reset_rvm_path __result
  # detect path to RVM
  if
    test -z "$rvm_path"
  then
    reset_rvm_path=true
    if test -n "${BASH_SOURCE:-$_}" -a -f "${BASH_SOURCE:-$_}"
    then
      export rvm_path="${BASH_SOURCE:-$_}"
      rvm_path="` \command \cd "${rvm_path%/scripts/extras/chruby.sh}">/dev/null; pwd `"
    elif test -x "$HOME/.rvm/bin/rvm"
    then export rvm_path="$HOME/.rvm"
    elif test -x "/usr/local/rvm/bin/rvm"
    then export rvm_path="/usr/local/rvm"
    else return 127
    fi
  fi
  __result=0
  # handle rvm "use" and other sub-commands separately
  if
    test "$1" = "use"
  then
    if
      rvm_project_environment="`"${rvm_path:-}/bin/rvm" . do rvm env --path 2>/dev/null`" &&
      test -n "${rvm_project_environment:-}" -a -s "${rvm_project_environment:-}"
    then
      \. "${rvm_project_environment:-}" || __result=$?
    else
      __result=$?
    fi
  else
    "$rvm_path/bin/rvm" "$@" || __result=$?
  fi
  # cleanup
  if test -n "${reset_rvm_path:-}"
  then unset rvm_path reset_rvm_path
  fi
  return ${__result}
}
```
I just wrote it without testing 1) it should work but there might be some small bugs 2) it's `sh` not `tcsh` - so might still need some work

please let me know if you get working version, I can add it to `scripts/extras/` and add code to automatically install it for `tcsh`.

**Comment by vensridev** [comment]
Thanks Mpapis. I will try this out and provide you feedback.

**Comment by vensridev** [comment]
Hi Mpapis, 

Can we install RVM in a non-default location? I have restricted space in $HOME and can't afford installing all versions of Ruby and other stuffs in here.

Thanks

**Comment by vensridev** [comment]
is http://stackoverflow.com/questions/15282509/how-to-change-rvm-install-location the only way out?

**Comment by mpapis** [comment]
setting `rvm_path` in `~/.rvmrc` is the best way, you can also pass on flag to installer:
```bash
\curl -sSL https://get.rvm.io | bash -s head --path /different/path
```

**Comment by vensridev** [comment]
I will try --path next time I install RVM. Thanks Mpapis

**Comment by vensridev** [comment]
Hi Mpapis,

When I try installing RVM single-user mode, why does it using yum, which requires root password, which I do not have. It also says, it is trying system-wide install. I'm confused. Can you help me in installing RVM without root access requirement?

        bash-4.1$ \curl -sSL https://get.rvm.io | bash -s stable --path <path-edited>/softwares/RVM --ruby --rails
        Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
        Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
        gpg: Signature made Wed Jan 7 17:25:10 2015 IST using RSA key ID BF04FF17
        gpg: Good signature from "Michal Papis (RVM signing) mpapis@gmail.com"
        gpg: WARNING: This key is not certified with a trusted signature!
        gpg: There is no indication that the signature belongs to the owner.
        Primary key fingerprint: 409B 6B17 96C2 7546 2A17 0311 3804 BB82 D39D C0E3
        Subkey fingerprint: 62C9 E5F4 DA30 0D94 AC36 166B E206 C29F BF04 FF17
        GPG verified '<path-edited>/softwares/RVM/archives/rvm-1.26.9.tgz'
        Creating group 'rvm'
        user password required for 'groupadd rvm':

        sudo: 1 incorrect password attempt

        Installing RVM to <path-edited>/softwares/RVM/

        chown: invalid group: :rvm'
        could not set group of '<path-edited>/softwares/RVM/man/man1', prefix the    command with 'rvmsudo' to fix it, if the situation persist report a bug.
        ...
        Warning! Installing RVM in system mode without root permissions, make sure to modify PATH / source rvm when it's needed.
        find: rvm' is not the name of an existing group
    Found 298 directories with mode different than '775',

Is this because of SSL key?. What am I doing wrong? I am installing RVM on Centos 6.4.

Please help.

**Comment by mpapis** [comment]
if you do not put your user name in the RVM path (not sure at which place it would need to be) then you need to add `--user-install` flag to the installer to let it know it's for one user only

**Comment by vensridev** [comment]
Hi Mpapis,

It doesn't work the way we expected. The command line that I use is:

        \curl -sSL https://get.rvm.io | bash -s stable --ruby --rails --user-install

After installing RVM in $HOME/.rvm the flow goes ahead and I guess try installing Ruby and prompts for password of root I guess, as my Linux password fails.


        #
        #   Thank you for using RVM!
        #   We sincerely hope that RVM helps to make your life easier and more enjoyable!!!
        #
        # ~Wayne, Michal & team.

        In case of problems: http://rvm.io/help and https://twitter.com/rvm_io

        Upgrade Notes:

          * No new notes to display.

        rvm 1.26.9 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
        Searching for binary rubies, this might take some time.
        No binary rubies available for: centos/6/x86_64/ruby-2.2.0.
        Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
        Checking requirements for centos.
        Installing requirements for centos.
        Installing required packages: libyaml-devel..User password required for 'yum install -y libyaml-devel': 

What am I doing wrong? Can you help?

Thanks in advance.

**Comment by mpapis** [comment]
RVM uses `sudo` - try `sudo ls` - and it will tell you which password you need

**Comment by mpapis** [comment]
closing as there was no feedback in some time, if anyone has similar problems open a new ticket
