### ISSUE TITLE
Problem installing RVM on OSX Yosemite

### ISSUE THREAD

**Issue by codematix** [wayneeseguin/rvm#3257]
I am encountering the following errors while attempting to install RVM on my Mac OSX Yosemite:

``` shell
λ ~/ \curl -sSL https://get.rvm.io | bash -s stable
Downloading https://github.com/wayneeseguin/rvm/archive/1.26.9.tar.gz
Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc
Found PGP signature at: 'https://github.com/wayneeseguin/rvm/releases/download/1.26.9/1.26.9.tar.gz.asc',
but no GPG software exists to validate it, skipping.
./scripts/install:set:14: no such option: errtrace
```

I am using `zsh` and `ruby` version `ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]` which comes standard with Mac OSX.

Please let me know if I am missing something.

**Comment by robdodson** [comment]
Running into the same issue on OSX Yosemite. Also using `zsh`.

**Comment by codematix** [comment]
Some success when I made another attempt by doing the following:

``` shell
cd ~/.rvm/src/rvm
./scripts/install
```

This seemed to run `rvm` successfully. But I am not sure if this does all the required installation operations.

**Comment by robdodson** [comment]
Yeah I also found that if I changed my shell to bash `chsh -s /bin/bash` and re-ran the install command `\curl -sSL https://get.rvm.io | bash -s stable` everything worked.

**Comment by codematix** [comment]
Weird! This was not happening to me before.

P.S. I am running Yosemite. Not sure why I mentioned Mavericks :-P

**Comment by hackeryoung** [comment]
I also ran into the same issue. It's a bit frustrated :(

**Comment by mpapis** [comment]
this should do it, please let me know if there are still issues with installing

**Comment by Ger123** [comment]
Hi, I entered the command
\curl -sSL https://get.rvm.io | bash -s stable
But I get back “unable to get local issuer certificate” it advises using the -k switch but that doesn’t work either. I downloaded the gpg tool suite as advised from the RVM website. Anyone else having the same problem!

**Comment by mpapis** [comment]
@Ger123 please open a new ticket with your commands and full output

**Comment by iAshabaliev** [comment]
a
