### ISSUE TITLE
"stack level too deep" error on Mac OS X 10.10.1 while installing 2.2.0

### ISSUE THREAD

**Issue by plashchynski** [wayneeseguin/rvm#3259]
~% rvm install 2.2.0
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-2.2.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/daniel/.rvm/rubies/ruby-2.2.0, this may take a while depending on your cpu(s)...
ruby-2.2.0 - #downloading ruby-2.2.0, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.6M  100 12.6M    0     0  1663k      0  0:00:07  0:00:07 --:--:-- 1629k
ruby-2.2.0 - #extracting ruby-2.2.0 to /Users/daniel/.rvm/src/ruby-2.2.0 - please wait
ruby-2.2.0 - #applying patch /Users/daniel/.rvm/patches/ruby/2.2.0/fix_installing_bundled_gems.patch - please wait
ruby-2.2.0 - #configuring - please wait
ruby-2.2.0 - #post-configuration - please wait
ruby-2.2.0 - #compiling - please wait
ruby-2.2.0 - #installing - please wait
Error running '__rvm_make install',
showing last 15 lines of /Users/daniel/.rvm/log/1420997688_ruby-2.2.0/install.log
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /Users/daniel/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              minitest-5.4.3.gem
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:723:in `block in <main>': stack level too deep (SystemStackError)
	from ./tool/rbinstall.rb:749:in `call'
	from ./tool/rbinstall.rb:749:in `block in <main>'
	from ./tool/rbinstall.rb:746:in `each'
	from ./tool/rbinstall.rb:746:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2
There has been an error while running make install. Halting the installation.
~% rvm --version
rvm 1.26.9 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

**Comment by mpapis** [comment]
please try:
```bash
rvm get head
rvm reload
rvm remove 2.2
rvm install 2.2
```

**Comment by plashchynski** [comment]
Hey @mpapis,
unfortunately that doesn't help. The same issue. Btw ```make install``` in the rvm ruby sources directory runs successfully.

**Comment by webhive** [comment]
Confirm - just got exactly the same issue on clear fresh MacOS installation

```
% rvm reinstall 2.2.0
ruby-2.2.0 - #removing src/ruby-2.2.0 - please wait
ruby-2.2.0 - #removing rubies/ruby-2.2.0 - please wait
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.10/x86_64/ruby-2.2.0.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/roman/.rvm/rubies/ruby-2.2.0, this may take a while depending on your cpu(s)...
ruby-2.2.0 - #downloading ruby-2.2.0, this may take a while depending on your connection...
ruby-2.2.0 - #extracting ruby-2.2.0 to /Users/roman/.rvm/src/ruby-2.2.0 - please wait
ruby-2.2.0 - #applying patch /Users/roman/.rvm/patches/ruby/2.2.0/fix_installing_bundled_gems.patch - please wait
ruby-2.2.0 - #configuring - please wait
ruby-2.2.0 - #post-configuration - please wait
ruby-2.2.0 - #compiling - please wait
ruby-2.2.0 - #installing - please wait
Error running '__rvm_make install',
showing last 15 lines of /Users/roman/.rvm/log/1421400023_ruby-2.2.0/install.log
                              json 1.8.1
                              psych 2.0.8
                              rake 10.4.2
                              rdoc 4.2.0
installing bundle gems:       /Users/roman/.rvm/rubies/ruby-2.2.0/lib/ruby/gems/2.2.0 (build_info, cache, doc, extensions, gems, specifications)
                              minitest-5.4.3.gem
                              power_assert-0.2.2.gem
                              test-unit-3.0.8.gem
./tool/rbinstall.rb:723:in `block in <main>': stack level too deep (SystemStackError)
	from ./tool/rbinstall.rb:749:in `call'
	from ./tool/rbinstall.rb:749:in `block in <main>'
	from ./tool/rbinstall.rb:746:in `each'
	from ./tool/rbinstall.rb:746:in `<main>'
make: *** [do-install-nodoc] Error 1
+__rvm_make:0> return 2
There has been an error while running make install. Halting the installation.
```

**Comment by qinix** [comment]
got the same issue on clear fresh MacOS installation too

**Comment by vincentbarr** [comment]
+1. Same error after a fresh installation of OS X Yosemite. 

Tried suggestion below without success: 

> rvm get head
> rvm reload
> rvm remove 2.2
> rvm install 2.2

**Comment by yuankui** [comment]
the same issue..
ruby-2.2.0

**Comment by jeffshantz** [comment]
+1

**Comment by mpapis** [comment]
needed to fix the "fix patch", please try again:
```bash
rvm get head
rvm reload
rvm remove 2.2
rvm install 2.2
```

**Comment by webhive** [comment]
work well now

```
rvm get head
rvm reinstall 2.2.0
```

**Comment by jeffshantz** [comment]
@mpapis Thank you, it now works.

**Comment by plashchynski** [comment]
now it works, thank you!
