### ISSUE TITLE
rvm install ruby-2.1.4 restart computer

### ISSUE THREAD

**Issue by adolfopeccin** [wayneeseguin/rvm#3261]
Hello, I'm trying to install the ruby 2.1.4 but when i run 'rvm install ruby-2.1.4' after 'configuring... please wait.' the computer restarts.

Model Name:	MacBook Pro
Model Identifier:	MacBookPro9,1
System Version:	OS X 10.10.1 (14B25)
Kernel Version:	Darwin 14.0.0

Thank you!

**Comment by mpapis** [comment]
let's start with [gisting](https://gist.github.com) `env | sort` and `alias`

**Comment by adolfopeccin** [comment]
[This?](https://gist.github.com/adolfopeccin/ee4b44e8bf48379b00a5)

**Comment by mpapis** [comment]
nothing there, try this way:
```bash
rvm install 2.1.4 --trace 2>&1 | tee ~/2.1.4-big.log
```
and after restart you should have a log in `~/2.1.4-big.log` - please [gist it](https://gist.github.com)

**Comment by adolfopeccin** [comment]
I was looking and I think did not record all logs during installation... but [here](https://gist.github.com/adolfopeccin/9a6bdf1038beea3bf0a1)

**Comment by mpapis** [comment]
this is hard, try:
```bash
basename cd /Users/adolfopeccin/.rvm/archives
ls -l ruby-2.1.4.tar.bz2*
\command curl -C - -o ruby-2.1.4.tar.bz2.part http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.4.tar.bz2
```

**Comment by adolfopeccin** [comment]
I did the:
```
cd /Users/adolfopeccin/.rvm/archives
ls -l ruby-2.1.4.tar.bz2*
\command curl -C - -o ruby-2.1.4.tar.bz2.part http://cache.ruby-lang.org/pub/ruby/2.1/ruby-2.1.4.tar.bz2
```

And the `rvm install 2.1.4` worked.
Thank you sir.

*** The gist of completed install [here](https://gist.github.com/adolfopeccin/0c71d64bc3ce6347fc8e)

**Comment by mpapis** [comment]
bizarre, glad it works, not sure why it restarts, if it's end of the problems please close the ticket
