### ISSUE TITLE
OS X: Error when installing any gem - gem install bundler ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:           Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

### ISSUE THREAD

**Issue by gmangalo** [wayneeseguin/rvm#3264]
OS X 10.9.5
Gem 2.0.14
Ruby 2.0.0p481
OpenSSL 0.9.8za 5 Jun 2014

gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)

Tried adding source tag
gem install bundler --source http://rubygems.org
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/latest_specs.4.8.gz)
          Unable to download data from http://rubygems.org/ - no such name (http://rubygems.org/latest_specs.4.8.gz)

Thought of using stable ruby version through RVM -  \curl -sSL https://get.rvm.io | bash -s stable --ruby but I am getting this error
curl: (6) Could not resolve host: get.rvm.io

**Comment by mpapis** [comment]
can I see `cat /etc/resolv.conf`? it is possible:

- your network configuration is broken,
- your network is broken (could be temporary - please retry)

**Comment by gmangalo** [comment]
thanks @mpapis this issue was related to our network's firewall, needed to install using a wifi and bundler was successfully installed now.

**Comment by vasanthaneppali** [comment]
@mpapis
hi am facing the same and here is my resil.conf 
# Generated by NetworkManager
nameserver 10.87.61.13
nameserver 10.170.67.165
nameeserver 8.8.8.8

what needs to be done in resolv.conf can you please share
thank you

**Comment by mpapis** [comment]
> @mpapis hi am facing the same and here is my resil.conf
Hey, your config looks good, if it has a `nameserver` especially the google one `8.8.8.8` everything should be fine, you might have a typo in the config - unless you made it writing it to the ticket.

Make sure your network configuration works as expected, it's not an rvm issue - it's your (system) network configuration.
