### ISSUE TITLE
Outdated docs or valid concern?

### ISSUE THREAD

**Issue by jasonnoble** [wayneeseguin/rvm#3275]
https://github.com/wayneeseguin/rvm/blob/master/help/rubygems.md states:

    Currently only compatible with MRI 1.8., 1.9. and Ruby Enterprise Edition. If your system is not 
    supported, running the command will generate an error message.

I've run `rvm rubygems latest` with Ruby 2.1.5 and it seems to not have any issues.  Should the help docs be updated?  

Perhaps it's only compatible with MRI and Ruby Enterprise Edition?

**Comment by mpapis** [comment]
this should do it

**Comment by jasonnoble** [comment]
Thanks!
