### ISSUE TITLE
Ubuntu multi-user installation not working (because of UID variable)

### ISSUE THREAD

**Issue by tiangolo** [wayneeseguin/rvm#3276]
The multi-user installation is not working in Ubuntu, because the script checks if it was run with sudo using ` UID == 0 `, but that doesn't work in Ubuntu 12.04 nor Ubuntu 14.04. 

You can check (at an Ubuntu machine) with:
```
$ echo $UID # should return a normal user ID number, as 1000
1000
$ sudo echo $UID # the script expects 0, but the result is the same as without sudo
1000
```

I also checked that under CentOS 6.5 and the behaviour is the same, so, probably the problem also occurs under CentOS 6.5.

I will submit now a pull request with the fix.

**Comment by mpapis** [comment]
how about:
```bash
echo $UID
sudo -i echo "\$UID"
```

**Comment by mpapis** [comment]
or even more accurate:
```bash
sudo bash -c 'echo $UID'
```

**Comment by tiangolo** [comment]
I already submitted a pull request with a fix: #3277 

What you suggest does work, but it also executes another bash session (if I'm not wrong).

In my pull request I suggest using `id -u`.

Would you check it out again?

If, after checking that pull request, you still prefer `bash -c 'echo $UID'`, I can change the code of the pull request to use that. And may I ask, why do you prefer that better?

**Comment by mpapis** [comment]
please provide the requested tests and https://github.com/wayneeseguin/rvm/pull/3277#issuecomment-72121311

**Comment by tiangolo** [comment]
OK, now I'm ashamed. I'm really sorry for making you lose your time.

I had understood that the multi-user install was just the same as the single-user install, but prefixed with `sudo`.

I was executing 

`sudo \curl -sSL https://get.rvm.io | bash -s stable`

instead of

`sudo \curl -sSL https://get.rvm.io | sudo bash -s stable`

**Comment by mpapis** [comment]
don't prefix `\curl` with `sudo` - the download process does not require `sudo` at all, it's just a network connection.
