### ISSUE TITLE
rbx-2.5.0 won't build on FreeBSD 10

### ISSUE THREAD

**Issue by rakaur** [wayneeseguin/rvm#3281]
FreeBSD 10 uses clang for the default system compiler. The first error was about no gcc, so I passed these options `rvm install rbx-2.5.0 -- --cc clang --cxx clang++`. After this it complained about not being able to find `llvm-config`, so I installed it from `/usr/ports/devel/llvm35`. You can either use `pkg install devel/llvm35` or you can install it from the port directory mentioned above with `make install distclean`. There are other versions of llvm, but the complaint mentioned it only supports 3.0-3.5. Even after this it will continue to not find `llvm-config` because it's actually installed as `/usr/local/bin/llvm-config35` so I created a symlink with `sudo ln -s /usr/local/bin/llvm-config35 /usr/local/bin/llvm-config`.

Now that all of that is taken care of, the build still fails. I've been told this might be a problem with rbx itself, but the error that occurs can be found [at this gist](https://gist.github.com/rakaur/c7d948d4a3a91b9891d6).

Thanks, and good luck.

**Comment by rakaur** [comment]
As it turns out, `gmake` wasn't installed. I hate `gmake`. I don't know why rvm or rbx didn't complain about it not being installed, probably because they assume if `make` is present it must be `gmake`, but unless you're on Linux it's going to be BSD make or some other make on any other platform. Most Unix OSes are not GNU userlands, people! :)

**Comment by rys** [comment]
FIxed by #3307
