### ISSUE TITLE
Having version without gemset name in .ruby-version means "use default gemset"

### ISSUE THREAD

**Issue by vs-adm** [wayneeseguin/rvm#3286]
The problem is when the contents of the `.ruby-version` file does not contain gemset name and `.ruby-gemset` is not created in the project folder, i.e.

    $ cat .ruby-version
    2.1.5

After cd in this directory the gemset used being reset to the empty value:

    $ rvm use 2.1.5@sample
    Using /Users/user/.rvm/gems/ruby-2.1.5 with gemset sample
    $ rvm gemset list
    gemsets for ruby-2.1.5 (found in /Users/user/.rvm/gems/ruby-2.1.5)
       (default)
    => sample
       global
       worker
    $ cd ~/project/dir
    $ cat .ruby-version
    2.1.5
    $ rvm gemset list
    gemsets for ruby-2.1.5 (found in /Users/user/.rvm/gems/ruby-2.1.5)
    => (default)
       sample
       global
       worker

The behaviour I expected is to keep the gemset selected unless otherwise declared explicitly. I understand that current behaviour may be the feature and if so there is a point of discussion here.

**Comment by mpapis** [comment]
the `(default)` gemset is used because there is no `.ruby-gemset` - a simple fix would be to create it:
```bash
echo sampe > .ruby-gemset
```
closing as current behavior is expected and we have [tests](https://github.com/wayneeseguin/rvm-test/blob/master/fast/ruby-version_comment_test.sh#L15-L39) for it

**Comment by vs-adm** [comment]
This simple fix is not so simple as I should run the project on about 20 different hosts with different gemsets names. Every host has default ruby with gemset selected and `.ruby-version` (but not `.ruby-gemset`) as a part of repository.

Having such landscape is near impossible to force every host to have one more gemset configuration file in the project directory and to sync it with the default ruby and gemset configuration.

I suggest you to re-think this behaviour or at least make an option to switch default gemset usage. If you find it suitable I probably can implement it.

**Comment by mpapis** [comment]
having 20 hosts I assume you would also have a configuration management tool like ansible, puppet or chef, even capistrano would be better then nothing, automating the creation of `.ruby-gemset` file  using one of those should be simple task.

RVM has option to disable gemsets - all it does is to disable any changes for gemsets - so the gemset would be ignored and you could just use the default gemset for everything ... but this would require configuring this option on all hosts - which gets you to the beginning.

as for implementing the "sticky" gemsets - RVM1 is closed for feature requests, such thing would be easily configurable via an plugin in RVM2 - but I need to find time to finish it first.

**Comment by vs-adm** [comment]
Thank you for reply. Ignoring gemsets completely could make the trick in my case. It's rather easy to add one line to the global config file than one file to each project on each host.

**Comment by mpapis** [comment]
you can read more about ignoring gemsets in the section `Rejection:` in `rvm help gemsets`
