### ISSUE TITLE
SLES12 does have libdb-4_8 but not libdb-4_5

### ISSUE THREAD

**Issue by kalabiyau** [wayneeseguin/rvm#3291]
That is brand new SLES from SUSE and probably we need to add support for it. As of current moment we don't have any difference bw sles and opensuse which are in fact a bit different

**Comment by rys** [comment]
Hopefully fixed in #3305

**Comment by rys** [comment]
Fixed in #3305

**Comment by kalabiyau** [comment]
@rys, thanks!
