### ISSUE TITLE
Installation ruby with rvm causing issue

### ISSUE THREAD

**Issue by rajkiran** [wayneeseguin/rvm#3297]
Hi, i am trying to install ruby on rvm(version - 1.26.10) and i am facing the following issue:

**Person-Mini:empmanagement krishna$ rvm install ruby-2.1.5p273
Searching for binary rubies, this might take some time.
No binary rubies available for: osx/10.7/i386/ruby-2.1.5p273.
Continuing with compilation. Please read 'rvm help mount' to get more information on binary rubies.
Checking requirements for osx.
Certificates in '/Users/krishna/homebrew/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/krishna/.rvm/rubies/ruby-2.1.5p273, this may take a while depending on your cpu(s)...
ruby-2.1.5p273 - #downloading ruby-2.1.5p273, this may take a while depending on your connection...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
curl: (22) The requested URL returned error: 404
The requested url does not exist(22): 'http://cache.ruby-lang.org/pub/ruby/./ruby-2.1.5p273.tar.bz2'
Checking fallback: http://ftp.ruby-lang.org/pub/ruby/./ruby-2.1.5p273.tar.bz2
Checking fallback: http://www.mirrorservice.org/sites/ftp.ruby-lang.org/pub/ruby/./ruby-2.1.5p273.tar.bz2
No fallback URL could be found, try increasing timeout with:

    echo "export rvm_max_time_flag=20" >> ~/.rvmrc

There has been an error fetching the ruby interpreter. Halting the installation. **

Please help me out. Thanks

**Comment by rys** [comment]
You need to provide a - character between the last minor digit and the p that defined the patch level. In this instance, 2.1.5 is no longer stable, 2.2.0 is, so patch releases aren't available any more.
