### ISSUE TITLE
Unknown ruby string (do not know how to handle): jruby-1.7.17

### ISSUE THREAD

**Issue by ginkel** [wayneeseguin/rvm#3300]
When issuing `rvm jruby-1.7.17 do rails c` I get:

    $ rvm jruby-1.7.17@`rvm gemset name` do rails c
    Unknown ruby string (do not know how to handle): jruby-1.7.17.

    $ ruby --version
    jruby 1.7.17 (1.9.3p392) 2014-12-09 fafd1a7 on OpenJDK 64-Bit Server VM 1.7.0_75-b13 +jit [linux-amd64]

    $ rvm --version
    rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

**Comment by ginkel** [comment]
Just found #3278, looks like a duplicate.

**Comment by fallwith** [comment]
See #3292

**Comment by mpapis** [comment]
closing as uplicate
