### ISSUE TITLE
No valid user IDs

### ISSUE THREAD

**Issue by jyr** [wayneeseguin/rvm#3303]
Hi,

I tried to install rvm in ubuntu 14.04 with:

    \curl -L https://get.rvm.io | bash -s stable --rails

and I have the messages:

    boletia@boletia-checkin:~$ \curl -L https://get.rvm.io | bash -s stable --rails
    % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
    100   184  100   184    0     0    787      0 --:--:-- --:--:-- --:--:--   789
    100 22817  100 22817    0     0  38861      0 --:--:-- --:--:-- --:--:--   98k
    Downloading https://github.com/wayneeseguin/rvm/archive/1.26.10.tar.gz
    Downloading https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc
     gpg: Signature made Mon Feb  2 10:09:00 2015 CST using RSA key ID BF04FF17
     gpg: Can't check signature: public key not found
     Warning, RVM 1.26.0 introduces signed releases and automated check of signatures when GPG software found.
     Assuming you trust Michal Papis import the mpapis public key (downloading the signatures).

     GPG signature verification failed for '/home/boletia/.rvm/archives/rvm-1.26.10.tgz' - 'https://github.com/wayneeseguin/rvm/releases/download/1.26.10/1.26.10.tar.gz.asc'!
     try downloading the signatures:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

    or if it fails:

    command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

    the key can be compared with:

    https://rvm.io/mpapis.asc
    https://keybase.io/mpapis

After run:

    gpg --keyserver hkp://keys.gnupg.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3

or 
   command curl -sSL https://rvm.io/mpapis.asc | gpg --import -

I have

    gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
    gpg: key D39DC0E3 was created 183689833 seconds in the future (time warp or clock problem)
    gpg: key D39DC0E3 was created 183689833 seconds in the future (time warp or clock problem)
    gpg: key D39DC0E3 was created 183689833 seconds in the future (time warp or clock problem)
    gpg: key D39DC0E3 was created 183689833 seconds in the future (time warp or clock problem)
    gpg: key D39DC0E3: no valid user IDs
    gpg: this may be caused by a missing self-signature
    gpg: Total number processed: 1
    gpg:           w/o user IDs: 1

What is the reason for gpg: key D39DC0E3: no valid user IDs? any tip?

Thanks

**Comment by karldotm** [comment]
jyr,

I am able to pull the same version using the same commands with no key issues.

I am using ntp for date sync'ing - is there any chance your time as ~2008-12-29 when you ran the install?

-karldotm

**Comment by havenwood** [comment]
@jyr The `no valid user IDs` warning you're seeing is caused by the "time warp" issue @karldotm points out, where your system time is set to a time in the distant past so it appears you're trying to validate an ID from the future. No time traveling!
