### ISSUE TITLE
[fish] when cd-ing to a directory with a .ruby-version file, I get complaints about return being used incorrectly

### ISSUE THREAD

**Issue by jaspertandy** [wayneeseguin/rvm#3311]
I've done all the setup [here](https://rvm.io/integration/fish), and this actually does what you expect, but I get an error thrown from a file that doesn't exist on line 0, so it's not really something I'm able to provide a lot of information on!

``/var/folders/h5/_512b0z562b5wl5gksw3_twr0000gn/T/rvm.fish.XXXXXXXXXX.lptBu68a: line 0: return: can only `return' from a function or sourced script``

The ruby version is a gemset that exists and is correctly selected. I just get this error message. Is it something I've done?

**Comment by havenwood** [comment]
Thanks for the report. I think this is a dup of #3262, which hasn't yet been resolved.

**Comment by jaspertandy** [comment]
I didn't think so when I saw it but having read it again I think you're probably right! Thanks and sorry for the dup.
