### ISSUE TITLE
Ruby 2.2.0 download time in Mavericks

### ISSUE THREAD

**Issue by Buzzlightyear90** [wayneeseguin/rvm#3312]
Here is the visual of downloading ruby: 
![skjermbilde 2015-02-20 kl 05 03 49 pm](https://cloud.githubusercontent.com/assets/10691093/6311015/7bcb0f42-b922-11e4-8665-2d3a60cc1e57.png)
I entered this command "brew update && brew install gmp && rvm install 2.2 --disable-binary" which doesn't seem to do anything. At the very last line, it has been saying configuring for the past five hours. I have been for the past three days trying to install ruby using the methods from these two websites: http://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/ and http://installfest.railsbridge.org/installfest/osx_rvm but I have waited almost 24 hours and I know it does not take this long to download. Even upgrading from Mountain Lion to Mavericks didn't take this long. This download is slowing down my computer and my internet connection has become not as fast. I just want to get ruby 2.2 on my computer so I can do the odin project which is like an online coding bootcamp but I can't continue on. How long does it take to download this? What is the problem?

**Comment by havenwood** [comment]
The configure script doesn't involve downloading but it can take a while. A good way to avoid compiling time is to use one of RVM's pre-compiled binaries.

I'd suggest using the 2.1.5 binary available for your system for the moment. You can install it with: `rvm install 2.1.5 --binary`

This avoids the configuring and compiling steps. When the 2.2.0 binary is available for your system you can easily upgrade but 2.1.5 should work well to start your bootcamp. Happy hacking!

**Comment by Buzzlightyear90** [comment]
It worked after ten hours. Now I am waiting for rails to install which has been almost two hours

**Comment by havenwood** [comment]
Well, I'm glad the 2.2.0 install succeeded. That's mighty slow! I'm guessing you're now waiting on building native extensions for various component gems of Rails? You might want to confirm that nothing else is taking up all of your cpu cycles, since it's taking inordinately long.

**Comment by Buzzlightyear90** [comment]
Yes I am on that but there nothing else I am running on my computer. My internet connection has been slow lately
