### ISSUE TITLE
another problem installing rails

### ISSUE THREAD

**Issue by Buzzlightyear90** [wayneeseguin/rvm#3316]
I installed using: 
gem install rails --no-ri --no-rdoc -V 
to install so I can see what is going on and I noticed that the moment it gets to this line: 
Running 'configure' for libxml2 2.9.2... 
it would hang for nine hours. When I control+C, I get this error:
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers. Check the mkmf.log file for more details. You may
need configuration options.

I look in the mkmf.log file and it is empty
This is my third day installing this

**Comment by rys** [comment]
Can you gist the output of `rvm info` so I can see what platform and rvm you're using, to try and debug it?
