### ISSUE TITLE
Add support for Ruby 2.0.0-p643 and 2.2.1

### ISSUE THREAD

**Issue by bjpe** [wayneeseguin/rvm#3329]
The above mentioned versions of the Ruby interpreter have just been released and can not be installed using RVM yet.

**Comment by alepore** [comment]
i actually did `rvm install 2.2.1` 4 days ago, should work

**Comment by bjpe** [comment]
Thank you, I just didn't try this because both versions were not listed under `rvm list known`. I don't know how this list is constructed, but it may be useful to update it.

**Comment by havenwood** [comment]
They'll be listed under `rvm list known` after #3322 and #3327 are merged.

**Comment by bjpe** [comment]
Thanks for the information!
