### ISSUE TITLE
rvm gemset default not staying default

### ISSUE THREAD

**Issue by txssseal** [wayneeseguin/rvm#3333]
I am attempting to set my default gemset using rvm --default use ruby-2.1.1@str

Once I cd .. and then cd back into the directory I set the default gemset, it reverts back to the old default gemset.

I saw there were previous issues with this in 2012.  I have tried rvm get head, and get master, neither are working.  What is a guy to do?

**Comment by havenwood** [comment]
Is there a `.rvmrc`, `.ruby-version` or `Gemfile` with `ruby=...` set in that directory?

**Comment by txssseal** [comment]
yes in the Gemfile

**Comment by havenwood** [comment]
By default RVM auto-switches if there is a ruby directive in your Gemfile: https://rvm.io/workflow/projects#project-file-gemfile
