### ISSUE TITLE
Possible to NOT use RedHat Network / Subscription Manager?

### ISSUE THREAD

**Issue by openface** [wayneeseguin/rvm#3335]
We'd like to use RVM on our RHEL6 hosts, but we do not have the root password.   Is it possible to somehow disable the use of RHN repositories, which seems to require the root password?

```
bash-4.2$ rvm requirements
Checking requirements for redhat.
jason password required for 'rhn-channel -l':
```

Thanks.

**Comment by havenwood** [comment]
You can disable autolibs and manually install the requirements: `rvm autolibs read-only`

**Comment by openface** [comment]
Thanks.  That's what I was looking for.
