### ISSUE TITLE
osx/10.10/x86_64/ruby-2.2.0.tar.bz2 contains /Users/haven in ruby-2.2.0/config

### ISSUE THREAD

**Issue by rogermarlow** [wayneeseguin/rvm#3360]
Looks like a ruby installation configured by /Users/haven has made its way onto rvm_io.global.ssl.fastly.net

This is what I see on a MacBook Pro Darwin Kernel Version 14.1.0
```
$ rvm version
rvm 1.26.10 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ rvm install ruby-2.2.0
Searching for binary rubies, this might take some time.
Found remote file https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.2.0.tar.bz2
Checking requirements for osx.
Certificates in '/usr/local/etc/openssl/cert.pem' are already up to date.
Requirements installation successful.
ruby-2.2.0 - #configure
ruby-2.2.0 - #download
ruby-2.2.0 - #validate archive
ruby-2.2.0 - #extract
ruby-2.2.0 - #validate binary
ruby-2.2.0 - #setup
ruby-2.2.0 - #gemset created /Users/rogermarlow/.rvm/gems/ruby-2.2.0@global
ruby-2.2.0 - #importing gemset /Users/rogermarlow/.rvm/gemsets/global.gems..........................................
ruby-2.2.0 - #generating global wrappers........
ruby-2.2.0 - #gemset created /Users/rogermarlow/.rvm/gems/ruby-2.2.0
ruby-2.2.0 - #importing gemsetfile /Users/rogermarlow/.rvm/gemsets/default.gems evaluated to empty gem list
ruby-2.2.0 - #generating default wrappers........
```
So far so good. But when I try to install gems with native extensions, e.g. json, it fails complaining that `/Users/haven` is not a valid directory for the linker:
```
$ gem install json
Fetching: json-1.8.2.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    /Users/rogermarlow/.rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150328-27638-19v1fva.rb extconf.rb
creating Makefile

make "DESTDIR=" clean

make "DESTDIR="
compiling generator.c
linking shared-object json/ext/generator.bundle
ld: warning: directory not found for option '-L/Users/haven/.sm/pkg/active/lib'

make "DESTDIR=" install
make: /usr/local/bin/gmkdir: No such file or directory
make: *** [.RUBYARCHDIR.-.json.-.ext.time] Error 1

make install failed, exit code 2

Gem files will remain installed in /Users/rogermarlow/.rvm/gems/ruby-2.2.0/gems/json-1.8.2 for inspection.
Results logged to /Users/rogermarlow/.rvm/gems/ruby-2.2.0/extensions/x86_64-darwin-14/2.2.0-static/json-1.8.2/gem_make.out
```

Note the `/Users/haven` in the generated Makefile. It comes from the tarball that rvm downloaded:
```
$ curl https://rvm_io.global.ssl.fastly.net/binaries/osx/10.10/x86_64/ruby-2.2.0.tar.bz2 -o ruby-2.2.0.tar.bz2
$ tar xjf ruby-2.2.0.tar.bz2
$ grep -rn '/Users/haven' ruby-2.2.0
Binary file ruby-2.2.0/bin/ruby matches
ruby-2.2.0/config:14:CFLAGS="-O3 -I/Users/haven/.sm/pkg/active/include -fPIC -mmacosx-version-min=10.7 -pipe"
ruby-2.2.0/config:64:LDFLAGS="-L. -L/Users/haven/.sm/pkg/active/lib -fPIC -Bstatic -fstack-protector -L/usr/local/lib"
[about 480 other lines where /User/haven appears]
```

**Comment by havenwood** [comment]
@rogermarlow Previous binaries built by mpapis have `/Users/mpapis` in `ruby-x.y.z/config`--they're just `/Users/haven` instead when I built them. This itself shouldn't be a problem, but you're running into an issue with yesterday's binaries depending on coreutils.

The OS X binaries from yesterday errantly depended on coreutils. All of the affected binaries have now been replaced with updated versions that work without coreutils. If you uninstall, `rvm cleanup all`, and reinstall the binary you should no longer run into the `/usr/local/bin/gmkdir: No such file or directory` error. Alternatively you could `brew install coreutils` and not update the binary.

**Comment by havenwood** [comment]
@rogermarlow Or to compile yourself instead of using the precompiled binary you can `rvm reinstall 2.2.0 --disable-binary`. My apologies for the `coreutils` error. I'm working the kinks out of making new OS X binaries available.

**Comment by rogermarlow** [comment]
@havenwood thanks for the quick response. I am back up and running without having to install coreutils. It's not really my bailiwick but I am surprised that the binaries are distributed with something like the home directory of the distributing developer baked into them.

**Comment by havenwood** [comment]
@rogermarlow The `ruby-2.2.0/config` file is created by RVM as a log of the build. When you install the binary a new `ruby-2.2.0/config` will be generated for your install location. There are a couple artifacts from the SM Framework build that remain that could probably be removed. We're looking into various options for OS X builds going forward.

**Comment by mpapis** [comment]
`ld: warning: directory not found for option '-L/Users/haven/.sm/pkg/active/lib'` - is only a warning, 

the real problem is:
`make: /usr/local/bin/gmkdir: No such file or directory`

which should be fixed, try: `rm $rvm_path/archives/bin-ruby-2.2.0.tar.bz2 && rvm reinstall ruby-2.2.0 --binary`

**Comment by robdbirch** [comment]
I think this may crept back into the new release:

creating Makefile

make "DESTDIR=" clean

...
make "DESTDIR="
compiling breakpoint.c
compiling context.c
compiling debase_internals.c
compiling locker.c
linking shared-object debase_internals.bundle
ld: warning: directory not found for option '-L/Users/travis/.sm/pkg/active/lib'

make "DESTDIR=" install
make: /usr/local/bin/gmkdir: No such file or directory
make: *** [.RUBYARCHDIR.time] Error 1

rvm version
rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]

OS X 10.11.4 (15E65)

**Comment by chadjoseph** [comment]
@robdbirch I'm on OS X 10.11.4, with full Xcode 7.3.1, Ruby 2.2.5, RVM 1.27.0 and this is a problem for me as well.

**Comment by robdbirch** [comment]
@chadjoseph I got around it by creating a symbolic from /usr/bin/mkdir  to /usr/local/bin/gmkdir

**Comment by snepote** [comment]
Thanks @chadjoseph! _coreutils_ really solved the problem from me.
- OS X El Capitan 10.11.6, rvm 1.27.0, Ruby 2.2.5

**Comment by pkuczynski** [comment]
@snepote how did you installed `coreutils`? Homebrew?

**Comment by snepote** [comment]
@pkuczynski, yes, Homebrew

**Comment by pkuczynski** [comment]
I will add `coreutils` as required package for macOS. This will solve the problem in the future :)
