### ISSUE TITLE
Determine path to wrapper binary for folder with .ruby-version

### ISSUE THREAD

**Issue by ralfebert** [wayneeseguin/rvm#3365]
In a shell script: Is there a way to determine the path to a wrapper binary for a given folder with a .ruby-version file?

This super-ugly workaround demonstrates what I am trying to accomplish:

```
DAEMON=`rvm $APP_PATH do which unicorn 2>/dev/null`
DAEMON=${DAEMON/gems/wrappers}
DAEMON=${DAEMON/bin\//}
```

Not getting this:
```
/usr/local/rvm/gems/ruby-2.2.1/bin/unicorn
```

But this:
```
/usr/local/rvm/wrappers/ruby-2.2.1/unicorn
```

(I'd like to have this for a init.d script where I just want to use rvm to give me the path to the wrapper binary that I need to run to get the correct ruby for the rails app that the script is supposed to run - I want to keep the script generic except for the path to the app folder)

**Comment by havenwood** [comment]
This is one way that would get you to the `gems/` wrapper path for the gem:
```bash
example_ruby="ruby-2.2.1"
example_gem="unicorn"

echo "$(rvm use $example_ruby do gem env gemhome)/wrappers/$example_gem"
#=> /usr/local/rvm/gems/ruby-2.2.1/wrappers/unicorn
```

**Comment by ralfebert** [comment]
Thanks! Got it to work based on your example.

Final solution:

```
# determine the unicorn wrapper that sets up the rvm ruby environment
# for the app according to its .ruby-version
RVM=/usr/local/rvm/bin/rvm
DAEMON="$($RVM in $APP_PATH do gem env gemhome)/wrappers/unicorn"
```
